services:
  app:
    build: ./docker
    restart: unless-stopped
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - mqtt
    volumes:
      - ./data:/app/data  

  mqtt:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data